apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      serviceAccountName: portainer-sa
      dnsPolicy: ClusterFirst
      containers:
      - name: portainer
        image: portainer/portainer-ce:2.33.6
        imagePullPolicy: IfNotPresent
        env:
        - name: EDGE_ID
          value: ""
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        - name: AGENT_SECRET
          value: "portainer-secret"
        args:
        - "--http-disabled"
        - "--tunnel-port=8000"
        ports:
        - containerPort: 9443
          name: https
        - containerPort: 8000
          name: edge
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: portainer-data
          mountPath: /data
      volumes:
      - name: portainer-data
        persistentVolumeClaim:
          claimName: portainer-data
