apiVersion: v1
kind: Secret
metadata:
  name: awx-mysql-secret
  namespace: awx
type: Opaque
stringData:
  password: "awx-mysql-password-change-me"
  database: "awx"
  username: "awx"
  host: "awx-mysql"
  port: "3306"
  type: "unmanaged"
