apiVersion: v1
kind: ServiceAccount
metadata:
  name: rundeck
  namespace: rundeck
---
{{- if .Values.rbac.clusterAdmin }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rundeck-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rundeck
  namespace: rundeck
{{- end }}
