apiVersion: v1
kind: Service
metadata:
  name: rundeck
  namespace: rundeck
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 4440
    protocol: TCP
    name: http
  selector:
    app: rundeck
